name: Android Build
on:
  push:
    branches: [ main ]
    paths:
      - 'packages/ui/**'
      - 'packages/android/**'
      - '.github/workflows/android.yml'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: install project dependencies
        run: npm install

      - name: build UI
        run: npm --prefix packages/ui run build:android

      - name: Install Briefcase
        run: |
          python -m pip install --upgrade pip
          pip install briefcase

      - name: Create Android App
        run: |
          cd packages/android
          briefcase create android
          briefcase build android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: omnigrab-android-apk
          path: packages/android/build/omnigrab/android/gradle/app/build/outputs/apk/debug/*.apk
